server:
  port: 9091

spring:
  application:
    name: authGateway
  
  # CORS 설정
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # OAuth2 Client 설정 (BFF가 Auth Server의 클라이언트)
  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-id: bff-client
            client-secret: "bff-secret"
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9091/api/auth/callback"
            scope: openid,profile,email
        provider:
          auth-server:
            authorization-uri: http://localhost:9090/oauth2/authorize
            token-uri: http://localhost:9090/oauth2/token
            user-info-uri: http://localhost:9090/userinfo
            jwk-set-uri: http://localhost:9090/.well-known/jwks.json

# 로깅 설정
logging:
  level:
    com.example.authgateway: DEBUG
    org.springframework.security: DEBUG