spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: ${app.service-names.eureka}

server:
  port: ${app.ports.eureka}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false